# Generated by Django 3.1.7 on 2021-04-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariomodel',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='password',
            field=models.TextField(db_column='usuario_contrasena', verbose_name='Contraseña del usuario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioApellido',
            field=models.CharField(db_column='usuario_apellido', max_length=45, verbose_name='Apellido del usuario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioCorreo',
            field=models.EmailField(db_column='usuario_correo', max_length=30, unique=True, verbose_name='Correo del usuario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioNombre',
            field=models.CharField(db_column='usuario_nombre', max_length=45, verbose_name='Nombre del usuario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioTipo',
            field=models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'USUARIO')], db_column='usuario_tipo', verbose_name='Tipo del usuario'),
        ),
    ]
