# Generated by Django 3.1.7 on 2021-04-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20210409_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='usuarioSueldo',
            field=models.DecimalField(db_column='usuario_sueldo', decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioId',
            field=models.AutoField(db_column='usuario_id', primary_key=True, serialize=False, unique=True),
        ),
    ]
