# Generated by Django 3.1.7 on 2021-04-16 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20210414_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosModel',
            fields=[
                ('gastosId', models.AutoField(db_column='gastos_id', primary_key=True, serialize=False, unique=True)),
                ('gastosFecha', models.DateField(db_column='gastos_fecha')),
                ('gastosNombreProducto', models.CharField(db_column='gastos_nombre', max_length=45, verbose_name='Nombre del producto')),
                ('gastosTipoPago', models.IntegerField(choices=[(1, 'EFECTIVO'), (2, 'TARJETA')], db_column='gastos_tipopago', verbose_name='Tipo de pago')),
                ('gastosPrecio', models.DecimalField(db_column='gastos_precio', decimal_places=2, max_digits=5, verbose_name='Precio del gasto')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='categoriaGastos', to='administracion.categoriamodel')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarioGastos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gastos',
                'db_table': 't_gastos',
            },
        ),
    ]
