# Generated by Django 3.1.7 on 2021-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_gastosmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gastosmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
